/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MelisekmAmbulanceWlList {
    }
}
declare global {
    interface HTMLMelisekmAmbulanceWlListElement extends Components.MelisekmAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMelisekmAmbulanceWlListElement: {
        prototype: HTMLMelisekmAmbulanceWlListElement;
        new (): HTMLMelisekmAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "melisekm-ambulance-wl-list": HTMLMelisekmAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MelisekmAmbulanceWlList {
    }
    interface IntrinsicElements {
        "melisekm-ambulance-wl-list": MelisekmAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "melisekm-ambulance-wl-list": LocalJSX.MelisekmAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMelisekmAmbulanceWlListElement>;
        }
    }
}
